data "aws_s3_bucket" "logging_bucket" {
  bucket = var.s3_logging_bucket
}

#tfsec:ignore:aws-s3-enable-versioning
resource "aws_s3_bucket" "acme_bucket" {
  bucket = var.bucket_name
  acl    = "public-read"
  logging {
    target_bucket = data.aws_s3_bucket.logging_bucket.id
    target_prefix = format("%s/logs/", var.bucket_name)
  }

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }
}

resource "aws_security_group" "bastion" {
  name        = "bastion_sg"
  description = "bastion_sg"
}

resource "cloudflare_record" "site_gmail_dkim" {
  # DKIM token generated by Google Workspace
  zone_id = data.cloudflare_zones.site_domain.zones[0].id
  name    = "google._domainkey"
  type    = "TXT"
  value   = file("${path.module}/gmail_dkim.txt")
}