name: build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Aqua Build Security
        uses: aquasecurity/tfsec-pr-commenter-action@v1.0.2-RC1
        with:
          github_token: ${{ github.token }}
          commenter_version: v1.0.2-RC1
